# Generated by Django 3.1 on 2020-12-01 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20201201_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 15, 43, 42, 254971)),
        ),
    ]
