# Generated by Django 3.1 on 2020-12-02 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20201202_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 15, 33, 28, 474661)),
        ),
    ]
